Repository Azure/aztfexport, pull requests merged in 2023-01, with the labels that each got.

#326 Interactive mode: `del` can be used for reverting skip
  .gitignore
  .vscode/launch.json
  internal/meta/importlist.go
  internal/meta/meta_map.go
  internal/meta/meta_query.go
  internal/meta/meta_res.go
  internal/meta/meta_rg.go
  internal/ui/importlist/importlist.go
  internal/ui/importlist/importlist_delegate.go
Labels: enhancement

#327 Don't push state if there is no state to push
  internal/meta/base_meta.go
Labels: bug

#332 Pipeline: Install .Net before ESRP task
  azure-pipelines.yml
Labels: deploy

#333 Update dep for provider v3.38.0
  go.mod
  go.sum
Labels: dependency

#322 New option `--module-path` to support appending to nested module
  go.mod
  go.sum
  internal/config/config.go
  internal/meta/base_meta.go
  internal/test/resourcegroup/module_test.go
  main.go
Labels: enhancement

#334 Fix the incorrect tfmerge version during a merge
  go.mod
  go.sum
Labels: bug

#335 Update acctest for compute: ubuntu image 16.04->18.04
  internal/test/cases/case_compute_vm_disk.go
Labels: test

#337 Fix mis-using Go `log` pkg
  internal/resourceset/azure_resource_set.go
  internal/ui/ui.go
Labels: bug

#340 Parallelize aztft and azlist
  go.mod
  go.sum
  internal/meta/meta_map.go
  internal/meta/meta_query.go
  internal/meta/meta_res.go
  internal/meta/meta_rg.go
  internal/resourceset/azure_resource_set.go
  internal/run.go
  internal/ui.go
Labels: performance

#341 Parallelize initializing provider in the importing directories
  go.mod
  go.sum
  internal/meta/base_meta.go
  main.go
Labels: enhancement

#342 Fix typo in README.md
  README.md
Labels: documentation

#346 `CommonConfig` explicitly takes Azure SDK credential, client option and additional provider configs from caller
  go.mod
  go.sum
  internal/client/client.go
  internal/meta/base_meta.go
  internal/meta/meta_query.go
  internal/meta/meta_res.go
  internal/meta/meta_rg.go
  internal/resourceset/azure_resource_set.go
  internal/test/cases/case_key_vault_nested_items.go
  internal/test/query/query_test.go
  internal/test/resmap/e2e_cases_test.go
  internal/test/resource/e2e_cases_test.go
  internal/test/resourcegroup/append_test.go
  internal/test/resourcegroup/e2e_cases_test.go
  internal/test/resourcegroup/module_test.go
  internal/test/utils.go
  main.go
  pkg/config/config.go
Labels: enhancement
