Repository Azure/aztfexport, pull requests merged in 2023-10, with the labels that each got.

#462 feature: add support for exporting to `azapi` provider
  .gitignore
  flag.go
  internal/meta/base_meta.go
  internal/meta/config_info.go
  internal/meta/meta_query.go
  internal/meta/meta_res.go
  internal/meta/meta_rg.go
  internal/resourceset/azure_resource_set.go
  main.go
  pkg/config/config.go
Labels: enhancement

#463 Update deps to support azurerm provider v3.77.0
  go.mod
  go.sum
Labels: dependency

#464 Update provider version (and dev-provider) handlings for azapi export
  README.md
  flag.go
  internal/meta/base_meta.go
  main.go
  pkg/config/config.go
Labels: documentation

#465 Update `tfadd` to make azapi export more useful & UI adpotion for azapi
  command_before_func.go
  go.mod
  go.sum
  internal/meta/base_meta.go
  internal/meta/meta_dummy.go
  internal/run.go
  internal/ui/importlist/importlist.go
  internal/ui/importlist/importlist_delegate.go
  internal/ui/ui.go
  main.go
  pkg/config/config.go
Labels: enhancement
